// Mock data for Product

import { Cart, Product } from "./types";

   export const products:Product[] = [
    {
      id: 1,
      title: "Classic White T-Shirt",
      image: ["/images/white-tshirt.jpg"],
      slug: "classic-white-tshirt",
      price: 20,
      category: ["Clothing", "T-Shirts"],
      description: "A high-quality classic white t-shirt made from 100% cotton.",
      size: "M",
      color: ["White"],
      qty: 100,
      discount: 10,
    },
    {
      id: 2,
      title: "Black Hoodie",
      image: ["/images/black-hoodie.jpg"],
      slug: "black-hoodie",
      price: 50,
      category: ["Clothing", "Hoodies"],
      description: "Stylish black hoodie with a comfortable fit.",
      size: "L",
      color: ["Black"],
      qty: 50,
      discount: 15,
    },
    {
      id: 3,
      title: "Running Shoes",
      image: ["/images/running-shoes.jpg"],
      slug: "running-shoes",
      price: 80,
      category: ["Footwear", "Sports"],
      description: "Durable and lightweight running shoes for athletes.",
      size: "42",
      color: ["Blue", "White"],
      qty: 30,
    },
  ];
  
  // Mock data for Cart
  export const Carts: Cart[] = [
    {
      id: 1,
      title: "Classic White T-Shirt",
      image: "/images/white-tshirt.jpg",
      slug: "classic-white-tshirt",
      price: 20,
      category: "Clothing",
      size: "M",
      color: "White",
      qty: 2,
      discount: 10,
    },
    {
      id: 3,
      title: "Running Shoes",
      image: "/images/running-shoes.jpg",
      slug: "running-shoes",
      price: 80,
      category: "Footwear",
      size: "42",
      color: "Blue",
      qty: 1,
    },
    {
        id: 4,
        title: "Running Shoes",
        image: "/images/running-shoes.jpg",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 5,
        title: "Running Shoes",
        image: "/",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 6,
        title: "Running Shoes",
        image: "/p6.png",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 7,
        title: "Running Shoes",
        image: "/p7.png",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 8,
        title: "Running Shoes",
        image: "/p8.png",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 9,
        title: "Running Shoes",
        image: "/p9.png",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
      {
        id: 10,
        title: "Running Shoes",
        image: "/p1.png",
        slug: "running-shoes",
        price: 80,
        category: "Footwear",
        size: "42",
        color: "Blue",
        qty: 1,
      },
  ];
  